Fix linker error for component build
This CL has two changes as below.
1) When build with gn option 'is_component_build = true'
below error occured.

error: duplicate symbol: MojoRetryInvitation

To fix this, use name |MojoRetryInvitationImpl|
instead of |MojoRetryInvitation| at entrypoints.cc.

2) Add additional guards for CASTANETS at thunks.cc.

Signed-off-by: v-saha <v.saha@samsung.com>